### ISSUE TITLE
Button Hover text color issue in Rust Style Variation

### ISSUE THREAD

**Issue by shail-mehta** [WordPress/twentytwentyfour#480] opened 2023-09-21 17:10 UTC
## **Description**
In Rust Style Default Button Text Color is not visible & in Outline Button Hover text Color  is not visible.

### **On Default Button hover:**
![rust-style](https://github.com/WordPress/twentytwentyfour/assets/22027190/a585f73c-47e7-431f-b832-5c4094e2d2f8)

### **On button outline Hover:**
![outline-button-on-hover](https://github.com/WordPress/twentytwentyfour/assets/22027190/4553f989-fd23-420b-921e-a9f29028ac41)

**Comment by MaggieCabrera** [comment] 2023-09-22 07:39
This is because Rust is not declaring contrast-2. Let's audit rust.json and replace with just the contrast color whenever theme.json uses contrast-2, that should work. And see about any of the other colors the variation doesn't use

**Comment by carolinan** [comment] 2023-09-25 02:20
But which color is supposed to be used for contrast-2?

**Comment by MaggieCabrera** [comment] 2023-09-25 08:41
> But which color is supposed to be used for contrast-2?

Contrast should be fine to use instead

**Comment by shail-mehta** [comment] 2023-09-25 15:58
@MaggieCabrera currently #A62B0C color use for contrast so need to use same color for contrast-2  or need to use another color ? (In Rust Style)

**Comment by MaggieCabrera** [comment] 2023-09-25 16:02
> @MaggieCabrera currently #A62B0C color use for contrast so need to use same color for contrast-2 or need to use another color ? (In Rust Style)

 We don't need to change the colors, we need to change where they are applied. If theme.json declares that the button hover color is `contrast-2` [here](https://github.com/WordPress/twentytwentyfour/blob/5622863cb068f25499550bf9c641bf0740b5964d/theme.json#L787), then we need to add a similar line in rust.json that declares that to be `contrast` instead. And probably check all other instances of `contrast-2` in the theme.json and see if they need to also be overridden in the style variation.

**Comment by shail-mehta** [comment] 2023-09-27 15:36
@MaggieCabrera it will work for default button hover color but it will override outline button hover? (because its defined in button-outline.css)

**for default button :**
`":hover": {
					"color": {
						"background": "var(--wp--preset--color--contrast)",
						"text": "var(--wp--preset--color--base)"
					}
				}`

**Comment by carolinan** [comment] 2023-10-06 06:26
I am testing the current trunk version of the theme and the default / filled button style in the rust variation has no hover style at all. The only indicator is the mouse cursor which is not enough to pass the accessibility-ready requirements.

**Comment by carolinan** [comment] 2023-10-06 06:27
Kind reminder that to test hover styles, you first need to add a link to the button, in the block toolbar.

**Comment by richtabor** [comment] 2023-10-13 19:49
I think we should remove the `wp_enqueue_block_style` for the custom outline variation style; I think it'll cause more trouble than it's worth; esp for variations

**Comment by MaggieCabrera** [comment] 2023-11-03 09:56
I just tested and can't reproduce this anymore, so I'm closing this

**Closed as completed by MaggieCabrera** 2023-11-03 09:56 UTC
Labels: [Type] Bug
