### ISSUE TITLE
Add translation support for static string in to the patterns/columns.php

### ISSUE THREAD

**Issue by devmuhib009** [WordPress/twentytwentyfour#97] opened 2023-08-27 13:03 UTC
Add translation support for static strings. All the Heading, Paragraphs are not translatable as per my recent check. Most of the strings are added with normal HTML tags.

To access and check the page, please visit with this path patterns/columns.php

**Comment by devmuhib009** [comment] 2023-08-27 13:17
I created the issue, as I did not noticed any issue created with this. But after checking in pull requests, I noticed a PR already created with ID #87

**Comment by juanfra** [comment] 2023-08-28 16:53
Thanks for creating this issue. I believe this is a duplicate of https://github.com/WordPress/twentytwentyfour/issues/37

**Closed as completed** 2023-08-28 23:18 UTC
Labels: Internationalization (i18n)
