### ISSUE TITLE
Latest Post Block alignment is not displaying properly with twenty-twentyfour theme

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/twentytwentyfour#730] opened 2023-11-24 05:41 UTC
**Description**
Hello Team,

I have worked on the theme "Twenty Twenty-Four" and found that the  **"Latest Post"** block **"Full width"** alignment is not displaying properly on the back-end side. When I checked this change on the front-end side, It looks good.

**Step-by-step reproduction instructions**

1. Go to page Type / to choose a block
2. Select **"Latest Post"** block
3. Select **"Full Width"** from the components toolbar group
4. Update the Page

**Expected behavior**

**Back-end:**
![latest_post_backend_01](https://github.com/WordPress/twentytwentyfour/assets/53076293/b91c79b2-be35-48d0-91c2-9b2b4d010edd)

**Front-end:**
![latest_post_frontend_01](https://github.com/WordPress/twentytwentyfour/assets/53076293/5145814b-1a2a-4b3f-a1c3-36dd6168d501)

**Screenshots**

**Back-end:**
![latest_post_backend_02](https://github.com/WordPress/twentytwentyfour/assets/53076293/e2992e19-6779-40ae-bb2c-c26397089e38)

![latest_post_backend_03](https://github.com/WordPress/twentytwentyfour/assets/53076293/684097b5-a844-422c-940e-446b92885b2d)

**Environment info**
Device: Macbook M1
OS: 13.6.1 (22G313)
Browser: Google Chrome
Version 119.0.6045.159 (Official Build) (arm64)
WordPress version:  6.4.1 running, Gutenberg 17.1.2, Theme active: Twenty Twenty-Four,

Thanks,

**Comment by carolinan** [comment] 2024-01-23 10:13
Thank you for reporting this issue.
I found that this is also a problem in Twenty Twenty-Three and Twenty Twenty-Two. But there are other block themes where this is not a problem, or where the problem is not visible.
I believe this is a problem with the difference in markup in the editor and the front, but it will need more dedicated testing.

**Comment by carolinan** [comment] 2024-01-23 10:23
We could try moving this issue to the Gutenberg repository, but I 'm not really sure if it is an editor or theme issue.

**Comment by carolinan** [comment] 2024-01-24 06:24
As linked above, I copied the issue to the Gutenberg repository.

**Closed as completed by carolinan** 2024-01-24 06:24 UTC
Labels: [Type] Bug
