### ISSUE TITLE
Audit template types assigned to each "template" pattern

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#453] opened 2023-09-20 22:09 UTC
The patterns prefixed with `template-` are unique in that they are suggested as full templates for replacing/using within the site editor. Let's make sure we're assigning the correct template types for each. 

- Archive alternative templates should only be available on any archive views (including category, tag, author)
- Page alternative templates should only be available for pages, not home/front-page. 
- Search alternative templates, only on search.
- Single templates should only be on page and posts.

We're using `page` a bit too much currently. For example, you wouldn't want to use a "search" template when you've decided to make a "page" template. Note that we do have a mechanism that affords you to choose the kind of template you want to build, so let's make sure the provided results fit the correct decisions. 

<img width="888" alt="CleanShot 2023-09-20 at 18 07 56" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/13f819f4-51d8-4fbd-9b64-54c9d28c8ae5">

**Comment by richtabor** [comment] 2023-09-20 22:10
For example, `twentytwentyfour/archive-writer` should have `

```
* Template Types: archive, category, tag, author, date
```

**Comment by MaggieCabrera** [comment] 2023-09-21 07:43
The thing is, if the theme is providing a search template already, the only way to see the option for search in this flow is to delete the template altogether. Something that is not apparent to the user and that is not doable at all from the editor. So by doing this we are effectively making impossible for the user to use or see the pattern in the editor UI in any circumstance.

**Comment by MaggieCabrera** [comment] 2023-09-21 09:56
Also, I think we should audit the usage of Post types, and see when and where we want to use page, post and/or wp_template. This might help with the issue I described above, but we need to make sure that all our patterns are discoverable, even if that means they show somewhere they ideally shouldn't.

**Comment by MaggieCabrera** [comment] 2023-09-22 09:11
### Template audit:

**footer-** files: these are all footer template part alternatives, they should show on footer create/replace flows. This is working as intended:

<img width="2072" alt="Screenshot 2023-09-22 at 10 55 01" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/e18eafdc-1a61-4b03-8657-45c9e4feafba">


**page-01** to **page-06** files: these are full page patterns. They should show on page creation (they are landing pages and home page alternatives). they have wp_template under Post types which makes them work inside existing templates, but they don't show in template creation flows, which I think is fine since they don't include headers/footers.

Page creation:

<img width="2147" alt="Screenshot 2023-09-22 at 10 55 59" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/369e7730-7709-424d-bdd3-6922a287af81">


**posts-** files: these are all query block alternatives, they should show on query block create/replace flows. These show mixed with the core alternatives, I don't know how to reorder them, is it by filename or slug?

<img width="2144" alt="Screenshot 2023-09-22 at 10 59 30" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/847d2ab5-5a1c-437a-9948-89f9466d0062">


**template-archive-** files: these are alternative pages to the archives. Should show for taxonomies (categories and tags) and author. This was only showing the main archive template. When applying the changes in #456 this is what appears when I create a new template for an author or specific category:

<img width="2134" alt="Screenshot 2023-09-22 at 11 01 40" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/0a1887b4-a984-45ec-8494-524d25b3f3ef">


**template-home-** files: these are home page alternatives (with footer and header included). Should show for home, front-page, index. As of today, these only work on front-page template creation flow. Can't be used to replace existing ones.

<img width="2163" alt="Screenshot 2023-09-22 at 10 56 57" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/5247d23a-2f92-4e87-90dc-c1d44e6a8409">


**template-index-** files: these are index template alternatives. Should show for index only. These don't show in any flows today.

**template-search-** files: these are search template alternatives. Should show for search only. Same as index

**template-single-** files: these are single template alternatives. Should single templates and posts. These can be used to replace the template of specific created pages, it won't work to change it on all of the posts. Also template-single-portfolio is not showing in the flow, it only shows for custom post types if you have them.


Right now index and search don't have a flow for them to show. Archive will work for cases of specific categories, but won't replace the original template defined for the theme, similar with single. The rest will be hidden from the user right now since there is no flow to reach them. 

I agree to remove page from the templates, since they are not even showing for pages right now anyway if you check my screenshots because of `Inserter: no`, but some of these patterns will not be used by users that don't know to remove files from their theme to make the creation flows work and surface the alternative patterns there.

---

Side note: Should RSVP be a full page template like newsletter landing is?

**Comment by MaggieCabrera** [comment] 2023-10-04 08:34
Since 6.4 will include a mechanism for swaping templates, let's close this one. I think https://github.com/WordPress/twentytwentyfour/pull/456 covers the initial concerns from this issue

**Closed as completed by MaggieCabrera** 2023-10-04 08:34 UTC
Labels: [Component] Templates
